# Manipulating array shapes


1.reshape()<br>
2.resize()<br>
3.flatten()<br>
4.revel()<br>
5.defining array shape()<br>

# reshape()

In [2]:
import numpy as np
a=np.array([[1,2,3],
           [4,5,6]])


In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.shape

(2, 3)

In [5]:
a_reshaped=np.reshape(a,(3,2))


In [6]:
a_reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
a_reshaped.shape

(3, 2)

In [8]:
a_reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])